version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
    networks:
      - techpronet

  myapp:
    build: .
    image: rahmatullah/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - techpronet

networks:
  techpronet:
    driver: bridge
